### ISSUE TITLE
Incorrect link for post "Continuously Deployed Mirage Unikernels with Google Compute Engine and CircleCI"

### ISSUE THREAD

**Issue by mjbright** [sgrove/riseos#1]
I was keen to read this article as I saw your video about use of MirageOS/Solo5 and how this allowed you to deploy on GCE.  Unfortunately the link on the blog/home page points to the mailgun article.

Continuously Deployed Mirage Unikernels with Google Compute Engine and CircleCI

**Comment by sgrove** [comment]
Sorry for the delay! I'm blocked on getting a reproducible build on CircleCI + OPAM, but here's the meat of the article https://gist.github.com/sgrove/09f86f4d2744e40980d0503e117d799d

**Comment by sgrove** [comment]
This should be fixed with the switch to the new blog setup!

**Comment by mjbright** [comment]
Great, it's fixed. Thanks a lot Sean!
